# Nivel 1

Desde un Jupyter Notebook realizarás los siguientes ejercicios utilizando la librería requests de Python.
Exploración básica con una API de laboratorio.

In [13]:
import requests
import pandas as pd
import json

In [ ]:
# 1. Consulta la API pública JSONPlaceholder utilizando el método GET para obtener:
# Lista de publicaciones (/posts)
# Lista de usuarios (/users)
# Lista de tareas (/todos)

# URLs de la API
url_posts = "https://jsonplaceholder.typicode.com/posts"
url_users = "https://jsonplaceholder.typicode.com/users"
url_todos = "https://jsonplaceholder.typicode.com/todos"

# Peticiones GET
res_posts = requests.get(url_posts)
res_users = requests.get(url_users)
res_todos = requests.get(url_todos)

# Convertir a JSON
posts = res_posts.json()
users = res_users.json()
todos = res_todos.json()

# 2. Muestra por pantalla:

# La cantidad total de cada recurso.
print("Cantidad total de posts:", len(posts))
print("Cantidad total de usuarios:", len(users))
print("Cantidad total de tareas:", len(todos))

# El código de estado de cada petición.
print("Código de estado /posts:", res_posts.status_code)
print("Código de estado /users:", res_users.status_code)
print("Código de estado /todos:", res_todos.status_code)

Cantidad total de posts: 100
Cantidad total de usuarios: 10
Cantidad total de tareas: 200
Código de estado /posts: 200
Código de estado /users: 200
Código de estado /todos: 200

In [ ]:
# 3. Realiza una petición a una publicación inexistente para obtener un error 404 y muestra el código de estado recibido.
peticion = requests.get("https://jsonplaceholder.typicode.com/posts/999999")

print("codigo de estado:", peticion.status_code)

codigo de estado: 404

In [ ]:
# 4. Realiza una petición POST para crear una nueva publicación ficticia. Incluye el título, el cuerpo del mensaje y un userId.
# Muestra la respuesta JSON.
# Muestra el código de estado.

nueva_publicacion = {
    "title": "Mi publicación ficticia",
    "body": "Este es el contenido del post",
    "userId": 1
}

respuesta_post = requests.post(
    "https://jsonplaceholder.typicode.com/posts",
    json=nueva_publicacion
)

print("Respuesta JSON:", respuesta_post.json())
print("Código de estado:", respuesta_post.status_code)

{
  "title": "Mi publicación ficticia",
  "body": "Este es el contenido del post",
  "userId": 1,
  "id": 101
}
Código de estado: 201
Respuesta JSON: {'title': 'Mi publicación ficticia', 'body': 'Este es el contenido del post', 'userId': 1, 'id': 101}

In [30]:
# 5. Realiza una petición PATCH para modificar parcialmente una publicación existente.
# Muestra la respuesta JSON.
# Muestra el código de estado.

modificacion = {
    "title": "Título actualizado"
}

respuesta_patch = requests.patch(
    "https://jsonplaceholder.typicode.com/posts/1",
    json=modificacion
)

print("Respuesta JSON:", respuesta_patch.json())
print("Código de estado:", respuesta_patch.status_code)

Respuesta JSON: {'userId': 1, 'id': 1, 'title': 'Título actualizado', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}
Código de estado: 200

In [3]:
# 6. Haz una petición DELETE sobre una publicación.
# Muestra la respuesta JSON.
# Muestra el código de estado.

respuesta_delete = requests.delete("https://jsonplaceholder.typicode.com/posts/1")

print("Respuesta JSON:", respuesta_delete.json())
print("Código de estado:", respuesta_delete.status_code)

Respuesta JSON: {}
Código de estado: 200

# Nivel 2
Interacción con una API pública real

1. Explora el repositorio de Public APIs y elige una API que permita realizar peticiones GET.

He elegido la API AviationStack, que permite obtener información sobre vuelos, aerolíneas y aeropuertos mediante peticiones GET.

2. Lee la documentación de la API:
Revisa la sección de endpoints disponibles. En un markdown, apunta al menos dos endpoints diferentes.

    GET /flights → Devuelve información de vuelos en tiempo real e históricos.
    GET /airports → Devuelve información de aeropuertos (códigos IATA, ICAO, país, ciudad, etc.).

Comprueba si ofrece filtros o parámetros opcionales interesantes. En un markdown, anótalos.

Parámetros y filtros interesantes
- flight_iata= Filtrar por código de vuelo.
- dep_iata=  Filtrar por aeropuerto de salida.
- arr_iata=  Filtrar por aeropuerto de llegada.
- airline_name=  Filtrar por aerolínea.
- limit=  Limitar el número de resultados.

In [11]:
# Verifica que la respuesta sea en formato JSON (es el más adecuado para este ejercicio)

url  ="http://api.aviationstack.com/v1/flights?access_key=54c5e0c3f5dea0e3555c94ec27667033&limit=5"
respuesta = requests.get(url)

print(respuesta.headers["Content-Type"])

application/json

In [ ]:
# 3. Haz una petición GET sencilla:
# Muestra el código de estado de la respuesta.
# Imprime de forma clara algunos de los campos de la respuesta JSON.

API_KEY = "54c5e0c3f5dea0e3555c94ec27667033"

url = f"http://api.aviationstack.com/v1/flights?access_key={API_KEY}&limit=5"

respuesta = requests.get(url)

print("Código de estado:", respuesta.status_code)

data = respuesta.json()

print(json.dumps(data, indent=4))

Código de estado: 200
{
    "pagination": {
        "limit": 5,
        "offset": 0,
        "count": 5,
        "total": 412965
    },
    "data": [
        {
            "flight_date": "2026-02-26",
            "flight_status": "scheduled",
            "departure": {
                "airport": "Tauranga",
                "timezone": "Pacific/Auckland",
                "iata": "TRG",
                "icao": "NZTG",
                "terminal": null,
                "gate": null,
                "delay": null,
                "scheduled": "2026-02-26T06:00:00+00:00",
                "estimated": "2026-02-26T06:00:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "arrival": {
                "airport": "Christchurch International",
                "timezone": "Pacific/Auckland",
                "iata": "CHC",
                "icao": "NZCH",
                "terminal": null,
                "gate": "14",
                "baggage": null,
                "scheduled": "2026-02-26T08:05:00+00:00",
                "delay": null,
                "estimated": null,
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "airline": {
                "name": "Air New Zealand",
                "iata": "NZ",
                "icao": "ANZ"
            },
            "flight": {
                "number": "5807",
                "iata": "NZ5807",
                "icao": "ANZ5807",
                "codeshared": null
            },
            "aircraft": {
                "registration": null,
                "iata": null,
                "icao": null,
                "icao24": "C82727"
            },
            "live": null
        },
        {
            "flight_date": "2026-02-26",
            "flight_status": "scheduled",
            "departure": {
                "airport": "Tauranga",
                "timezone": "Pacific/Auckland",
                "iata": "TRG",
                "icao": "NZTG",
                "terminal": null,
                "gate": null,
                "delay": null,
                "scheduled": "2026-02-26T06:00:00+00:00",
                "estimated": "2026-02-26T06:00:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "arrival": {
                "airport": "Christchurch International",
                "timezone": "Pacific/Auckland",
                "iata": "CHC",
                "icao": "NZCH",
                "terminal": null,
                "gate": "14",
                "baggage": null,
                "scheduled": "2026-02-26T08:05:00+00:00",
                "delay": null,
                "estimated": null,
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "airline": {
                "name": "Singapore Airlines",
                "iata": "SQ",
                "icao": "SIA"
            },
            "flight": {
                "number": "4537",
                "iata": "SQ4537",
                "icao": "SIA4537",
                "codeshared": {
                    "airline_name": "air new zealand",
                    "airline_iata": "nz",
                    "airline_icao": "anz",
                    "flight_number": "5807",
                    "flight_iata": "nz5807",
                    "flight_icao": "anz5807"
                }
            },
            "aircraft": {
                "registration": null,
                "iata": null,
                "icao": null,
                "icao24": "C82727"
            },
            "live": null
        },
        {
            "flight_date": "2026-02-26",
            "flight_status": "scheduled",
            "departure": {
                "airport": "Woodbourne Air Station",
                "timezone": "Pacific/Auckland",
                "iata": "BHE",
                "icao": "NZWB",
                "terminal": null,
                "gate": null,
                "delay": null,
                "scheduled": "2026-02-26T06:00:00+00:00",
                "estimated": "2026-02-26T06:00:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "arrival": {
                "airport": "Wellington International",
                "timezone": "Pacific/Auckland",
                "iata": "WLG",
                "icao": "NZWN",
                "terminal": null,
                "gate": null,
                "baggage": null,
                "scheduled": "2026-02-26T06:30:00+00:00",
                "delay": null,
                "estimated": null,
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "airline": {
                "name": "empty",
                "iata": null,
                "icao": null
            },
            "flight": {
                "number": "280",
                "iata": null,
                "icao": null,
                "codeshared": null
            },
            "aircraft": null,
            "live": null
        },
        {
            "flight_date": "2026-02-26",
            "flight_status": "scheduled",
            "departure": {
                "airport": "Woodbourne Air Station",
                "timezone": "Pacific/Auckland",
                "iata": "BHE",
                "icao": "NZWB",
                "terminal": null,
                "gate": null,
                "delay": null,
                "scheduled": "2026-02-26T06:00:00+00:00",
                "estimated": "2026-02-26T06:00:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "arrival": {
                "airport": "Auckland International",
                "timezone": "Pacific/Auckland",
                "iata": "AKL",
                "icao": "NZAA",
                "terminal": "D",
                "gate": "46",
                "baggage": null,
                "scheduled": "2026-02-26T07:30:00+00:00",
                "delay": null,
                "estimated": null,
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "airline": {
                "name": "Air New Zealand",
                "iata": "NZ",
                "icao": "ANZ"
            },
            "flight": {
                "number": "5208",
                "iata": "NZ5208",
                "icao": "ANZ5208",
                "codeshared": null
            },
            "aircraft": {
                "registration": null,
                "iata": null,
                "icao": null,
                "icao24": "C81A92"
            },
            "live": null
        },
        {
            "flight_date": "2026-02-26",
            "flight_status": "scheduled",
            "departure": {
                "airport": "Woodbourne Air Station",
                "timezone": "Pacific/Auckland",
                "iata": "BHE",
                "icao": "NZWB",
                "terminal": null,
                "gate": null,
                "delay": null,
                "scheduled": "2026-02-26T06:00:00+00:00",
                "estimated": "2026-02-26T06:00:00+00:00",
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "arrival": {
                "airport": "Auckland International",
                "timezone": "Pacific/Auckland",
                "iata": "AKL",
                "icao": "NZAA",
                "terminal": "D",
                "gate": "46",
                "baggage": null,
                "scheduled": "2026-02-26T07:30:00+00:00",
                "delay": null,
                "estimated": null,
                "actual": null,
                "estimated_runway": null,
                "actual_runway": null
            },
            "airline": {
                "name": "Singapore Airlines",
                "iata": "SQ",
                "icao": "SIA"
            },
            "flight": {
                "number": "4370",
                "iata": "SQ4370",
                "icao": "SIA4370",
                "codeshared": {
                    "airline_name": "air new zealand",
                    "airline_iata": "nz",
                    "airline_icao": "anz",
                    "flight_number": "5208",
                    "flight_iata": "nz5208",
                    "flight_icao": "anz5208"
                }
            },
            "aircraft": {
                "registration": null,
                "iata": null,
                "icao": null,
                "icao24": "C81A92"
            },
            "live": null
        }
    ]
}

In [16]:
# Mostrar algunos campos
for vuelo in data["data"]:
    print("Vuelo:", vuelo.get("flight", {}).get("iata"))
    print("Aerolínea:", vuelo.get("airline", {}).get("name"))
    print("Salida:", vuelo.get("departure", {}).get("airport"))
    print("Llegada:", vuelo.get("arrival", {}).get("airport"))
    print("---")

Vuelo: NZ5807
Aerolínea: Air New Zealand
Salida: Tauranga
Llegada: Christchurch International
---
Vuelo: SQ4537
Aerolínea: Singapore Airlines
Salida: Tauranga
Llegada: Christchurch International
---
Vuelo: None
Aerolínea: empty
Salida: Woodbourne Air Station
Llegada: Wellington International
---
Vuelo: NZ5208
Aerolínea: Air New Zealand
Salida: Woodbourne Air Station
Llegada: Auckland International
---
Vuelo: SQ4370
Aerolínea: Singapore Airlines
Salida: Woodbourne Air Station
Llegada: Auckland International
---

In [ ]:
# 4. Convierte los datos a un DataFrame de pandas:
df = pd.DataFrame(data["data"])
df.head()

,flight_date,flight_status,departure,arrival,airline,flight,aircraft,live
0,2026-02-25,scheduled,"{'airport': 'Wellington International', 'timez...","{'airport': 'Auckland International', 'timezon...","{'name': 'Air New Zealand', 'iata': 'NZ', 'ica...","{'number': '410', 'iata': 'NZ410', 'icao': 'AN...","{'registration': None, 'iata': None, 'icao': N...",None
1,2026-02-25,scheduled,"{'airport': 'Wellington International', 'timez...","{'airport': 'Auckland International', 'timezon...","{'name': 'Singapore Airlines', 'iata': 'SQ', '...","{'number': '4436', 'iata': 'SQ4436', 'icao': '...","{'registration': None, 'iata': None, 'icao': N...",None
2,2026-02-25,scheduled,"{'airport': 'Wellington International', 'timez...","{'airport': 'Auckland International', 'timezon...","{'name': 'Etihad Airways', 'iata': 'EY', 'icao...","{'number': '4624', 'iata': 'EY4624', 'icao': '...","{'registration': None, 'iata': None, 'icao': N...",None
3,2026-02-25,scheduled,"{'airport': 'Wellington International', 'timez...","{'airport': 'Auckland International', 'timezon...","{'name': 'EVA Air', 'iata': 'BR', 'icao': 'EVA'}","{'number': '3290', 'iata': 'BR3290', 'icao': '...","{'registration': None, 'iata': None, 'icao': N...",None
4,2026-02-25,scheduled,"{'airport': 'Wellington International', 'timez...","{'airport': 'Woodbourne Air Station', 'timezon...","{'name': 'Air New Zealand', 'iata': 'NZ', 'ica...","{'number': '5725', 'iata': 'NZ5725', 'icao': '...","{'registration': None, 'iata': None, 'icao': N...",None

# Nivel 3
API de Open Data Barcelona

In [ ]:
# 1. Utiliza la API de Open Data BCN para:
# Buscar un dataset de tu interés mediante package_search
url_search = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_search"

param_busqueda = {"q": "transport"}

respuesta = requests.get(url_search, params=param_busqueda).json()

# Mostrar el primer dataset encontrado
primer_dataset = respuesta["result"]["results"][0]
print("Primer dataset encontrado:")
print(json.dumps(primer_dataset, indent=4))


# package_show
dataset_id = primer_dataset["id"]

url_show = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show"
respuesta_show = requests.get(url_show, params={"id": dataset_id}).json()

# print(respuesta)
print(respuesta_show)

{
    "notes_translated": {
        "ca": "Nombre d'operacions d'aeronaus de l'aeroport Josep Tarradellas Barcelona-El Prat per principals pa\u00efsos de destinaci\u00f3 o origen   ",
        "en": "Number of aircraft operations at the Josep Tarradellas Barcelona-El Prat airport by main destination or origin countries",
        "es": "N\u00famero de operaciones de aeronaves del aeropuerto Josep Tarradellas Barcelona-El Prat por principales pa\u00edses de destino u origen"
    },
    "geolocation": "No",
    "dades_alt_valor": "Estadistica",
    "url_tornada": {
        "ca": "",
        "en": "",
        "es": ""
    },
    "dataset_fields_description": "__NOTA:__ La publicaci\u00f3 d'aquestes dades queda interrompuda el 5/1/2025. \r\nEsperem poder restablir-la el m\u00e9s aviat possible. Perdoneu les mol\u00e8sties ocasionades.",
    "fuente": "Flightradar24",
    "tag": "Vols,Aeroport,Companyies a\u00e8ries,Any 2019,Any 2020,Any 2021,Any 2022,Any 2023,Any 2024,Pa\u00efsos,Any 2025,Alt Valor",
    "private": false,
    "num_tags": 12,
    "code": "TransitAeri_FlightRadar_Ppal_Pais",
    "frequency": "MENSUAL",
    "id": "6ea9c163-e907-49fc-b916-bdddd1448e9e",
    "title_translated": {
        "ca": "Nombre d'operacions d'aeronaus de l'aeroport Josep Tarradellas Barcelona-El Prat per principals pa\u00efsos de destinaci\u00f3 o origen   ",
        "en": "Number of aircraft operations at the Josep Tarradellas Barcelona-El Prat airport by main destination or origin countries",
        "es": "N\u00famero de operaciones de aeronaves del aeropuerto Josep Tarradellas Barcelona-El Prat por principales pa\u00edses de destino u origen"
    },
    "metadata_modified": "2025-09-23T11:38:56.549389",
    "author": "Ger\u00e8ncia Municipal",
    "author_email": null,
    "isopen": true,
    "long_format": "Yes",
    "state": "active",
    "version": "",
    "mar_od": "Yes",
    "relationships_as_object": [],
    "department": "Oficina Municipal de Dades - Departament d'Estad\u00edstica i Difusi\u00f3 de Dades",
    "creator_user_id": "6d593275-d059-4261-9004-e6df8677e3bf",
    "type": "dataset",
    "resources": [
        {
            "cache_last_updated": null,
            "package_id": "6ea9c163-e907-49fc-b916-bdddd1448e9e",
            "datastore_active": true,
            "id": "daaf92f4-8879-40f0-bc35-d550f1f9582a",
            "api_access_number_absolute": "24",
            "state": "active",
            "api_access_number": "17",
            "size": "3362",
            "hash": "",
            "description": "",
            "format": "CSV",
            "downloads": "89",
            "last_modified": null,
            "url_type": null,
            "mimetype": null,
            "cache_url": null,
            "name": "2025_TransitAeri_FlightRadar_Ppal_Pais.csv",
            "created": "2025-03-26T09:00:20.385158",
            "url": "https://opendata-ajuntament.barcelona.cat/data/dataset/6ea9c163-e907-49fc-b916-bdddd1448e9e/resource/daaf92f4-8879-40f0-bc35-d550f1f9582a/download",
            "downloads_absolute": "97",
            "qa": "{'updated': '2026-02-25T02:13:23.738788', 'openness_score': 3, 'archival_timestamp': None, 'format': u'CSV', 'created': '2025-03-27T02:13:38.584219', 'resource_timestamp': None, 'openness_score_reason': u'This file had not been downloaded at the time of scoring it. URL extension \"csv\" relates to format \"CSV\" and receives score: 3.'}",
            "mimetype_inner": null,
            "position": 0,
            "revision_id": "7a87bddf-d3d5-4944-b97f-ea67a7b36a8e",
            "resource_type": null
        },
        {
            "api_access_number_absolute": "50",
            "cache_last_updated": null,
            "token_type": "",
            "package_id": "6ea9c163-e907-49fc-b916-bdddd1448e9e",
            "datastore_active": true,
            "id": "9b10dc6e-9266-4e33-935e-e10ed0dae343",
            "description": " ",
            "state": "active",
            "api_access_number": "21",
            "size": "242404",
            "token_required": "No",
            "hash": "",
            "token_name": "",
            "format": "CSV",
            "downloads": "255",
            "mimetype_inner": null,
            "url_type": null,
            "token_provider": "",
            "column_types": "",
            "hide_url": "No",
            "token_version": "",
            "mimetype": null,
            "cache_url": null,
            "name": "2024_TransitAeri_FlightRadar_Ppal_Pais.csv",
            "created": "2024-05-29T09:31:06.756252",
            "url": "https://opendata-ajuntament.barcelona.cat/data/dataset/6ea9c163-e907-49fc-b916-bdddd1448e9e/resource/9b10dc6e-9266-4e33-935e-e10ed0dae343/download",
            "downloads_absolute": "395",
            "map_visualization_res": "none",
            "qa": "{'updated': '2026-02-25T02:13:23.761835', 'openness_score': 3, 'archival_timestamp': None, 'format': u'CSV', 'created': '2024-05-31T02:08:40.233667', 'resource_timestamp': None, 'openness_score_reason': u'This file had not been downloaded at the time of scoring it. URL extension \"csv\" relates to format \"CSV\" and receives score: 3.'}",
            "last_modified": null,
            "position": 1,
            "revision_id": "7a87bddf-d3d5-4944-b97f-ea67a7b36a8e",
            "resource_type": null
        },
        {
            "api_access_number_absolute": "2",
            "cache_last_updated": null,
            "token_type": "",
            "package_id": "6ea9c163-e907-49fc-b916-bdddd1448e9e",
            "datastore_active": true,
            "id": "89cfba93-a038-4afe-adf5-599d879966d8",
            "description": " ",
            "state": "active",
            "api_access_number": "2",
            "size": "240300",
            "token_required": "No",
            "hash": "",
            "token_name": "",
            "format": "CSV",
            "downloads": "130",
            "mimetype_inner": null,
            "url_type": null,
            "token_provider": "",
            "column_types": "",
            "hide_url": "No",
            "token_version": "",
            "mimetype": null,
            "cache_url": null,
            "name": "2023_TransitAeri_FlightRadar_Ppal_Pais.csv",
            "created": "2024-05-29T09:31:49.618462",
            "url": "https://opendata-ajuntament.barcelona.cat/data/dataset/6ea9c163-e907-49fc-b916-bdddd1448e9e/resource/89cfba93-a038-4afe-adf5-599d879966d8/download",
            "downloads_absolute": "151",
            "map_visualization_res": "none",
            "qa": "{'updated': '2026-02-25T02:13:23.792891', 'openness_score': 3, 'archival_timestamp': None, 'format': u'CSV', 'created': '2024-05-31T02:08:40.244994', 'resource_timestamp': None, 'openness_score_reason': u'This file had not been downloaded at the time of scoring it. URL extension \"csv\" relates to format \"CSV\" and receives score: 3.'}",
            "last_modified": null,
            "position": 2,
            "revision_id": "7a87bddf-d3d5-4944-b97f-ea67a7b36a8e",
            "resource_type": null
        },
        {
            "api_access_number_absolute": "2",
            "cache_last_updated": null,
            "token_type": "",
            "package_id": "6ea9c163-e907-49fc-b916-bdddd1448e9e",
            "datastore_active": true,
            "id": "1d78cf40-9d04-4be0-bcee-8e075c9a77a0",
            "description": "",
            "state": "active",
            "api_access_number": "2",
            "size": "237692",
            "token_required": "No",
            "hash": "",
            "token_name": "",
            "format": "CSV",
            "downloads": "88",
            "mimetype_inner": null,
            "url_type": null,
            "token_provider": "",
            "column_types": "",
            "hide_url": "No",
            "token_version": "",
            "mimetype": null,
            "cache_url": null,
            "name": "2022_TransitAeri_FlightRadar_Ppal_Pais.csv",
            "created": "2024-05-29T09:32:06.818210",
            "url": "https://opendata-ajuntament.barcelona.cat/data/dataset/6ea9c163-e907-49fc-b916-bdddd1448e9e/resource/1d78cf40-9d04-4be0-bcee-8e075c9a77a0/download",
            "downloads_absolute": "95",
            "map_visualization_res": "none",
            "qa": "{'updated': '2026-02-25T02:13:23.822495', 'openness_score': 3, 'archival_timestamp': None, 'format': u'CSV', 'created': '2024-05-31T02:08:40.262138', 'resource_timestamp': None, 'openness_score_reason': u'This file had not been downloaded at the time of scoring it. URL extension \"csv\" relates to format \"CSV\" and receives score: 3.'}",
            "last_modified": null,
            "position": 3,
            "revision_id": "7a87bddf-d3d5-4944-b97f-ea67a7b36a8e",
            "resource_type": null
        },
        {
            "api_access_number_absolute": "2",
            "cache_last_updated": null,
            "token_type": "",
            "package_id": "6ea9c163-e907-49fc-b916-bdddd1448e9e",
            "datastore_active": true,
            "id": "c402f60b-5fb8-437a-bbbe-8976ac7ede51",
            "description": "",
            "state": "active",
            "api_access_number": "2",
            "size": "196089",
            "token_required": "No",
            "hash": "",
            "token_name": "",
            "format": "CSV",
            "downloads": "73",
            "mimetype_inner": null,
            "url_type": null,
            "token_provider": "",
            "column_types": "",
            "hide_url": "No",
            "token_version": "",
            "mimetype": null,
            "cache_url": null,
            "name": "2021_TransitAeri_FlightRadar_Ppal_Pais.csv",
            "created": "2024-05-29T09:32:24.031098",
            "url": "https://opendata-ajuntament.barcelona.cat/data/dataset/6ea9c163-e907-49fc-b916-bdddd1448e9e/resource/c402f60b-5fb8-437a-bbbe-8976ac7ede51/download",
            "downloads_absolute": "74",
            "map_visualization_res": "none",
            "qa": "{'updated': '2026-02-25T02:13:23.840694', 'openness_score': 3, 'archival_timestamp': None, 'format': u'CSV', 'created': '2024-05-31T02:08:40.272246', 'resource_timestamp': None, 'openness_score_reason': u'This file had not been downloaded at the time of scoring it. URL extension \"csv\" relates to format \"CSV\" and receives score: 3.'}",
            "last_modified": null,
            "position": 4,
            "revision_id": "7a87bddf-d3d5-4944-b97f-ea67a7b36a8e",
            "resource_type": null
        },
        {
            "api_access_number_absolute": "2",
            "cache_last_updated": null,
            "token_type": "",
            "package_id": "6ea9c163-e907-49fc-b916-bdddd1448e9e",
            "datastore_active": true,
            "id": "6d34a732-bdad-49e2-8231-7459120896d2",
            "description": "",
            "state": "active",
            "api_access_number": "2",
            "size": "159092",
            "token_required": "No",
            "hash": "",
            "token_name": "",
            "format": "CSV",
            "downloads": "71",
            "mimetype_inner": null,
            "url_type": null,
            "token_provider": "",
            "column_types": "",
            "hide_url": "No",
            "token_version": "",
            "mimetype": null,
            "cache_url": null,
            "name": "2020_TransitAeri_FlightRadar_Ppal_Pais.csv",
            "created": "2024-05-29T09:32:42.636403",
            "url": "https://opendata-ajuntament.barcelona.cat/data/dataset/6ea9c163-e907-49fc-b916-bdddd1448e9e/resource/6d34a732-bdad-49e2-8231-7459120896d2/download",
            "downloads_absolute": "82",
            "map_visualization_res": "none",
            "qa": "{'updated': '2026-02-25T02:13:23.869763', 'openness_score': 3, 'archival_timestamp': None, 'format': u'CSV', 'created': '2024-05-31T02:08:40.282041', 'resource_timestamp': None, 'openness_score_reason': u'This file had not been downloaded at the time of scoring it. URL extension \"csv\" relates to format \"CSV\" and receives score: 3.'}",
            "last_modified": null,
            "position": 5,
            "revision_id": "7a87bddf-d3d5-4944-b97f-ea67a7b36a8e",
            "resource_type": null
        },
        {
            "api_access_number_absolute": "5",
            "cache_last_updated": null,
            "token_type": "",
            "package_id": "6ea9c163-e907-49fc-b916-bdddd1448e9e",
            "datastore_active": true,
            "id": "790b7bb3-cc2a-48d7-82c0-ef51978bceb7",
            "description": "",
            "state": "active",
            "api_access_number": "4",
            "size": "121362",
            "token_required": "No",
            "hash": "",
            "token_name": "",
            "format": "CSV",
            "downloads": "85",
            "mimetype_inner": null,
            "url_type": null,
            "token_provider": "",
            "column_types": "",
            "hide_url": "No",
            "token_version": "",
            "mimetype": null,
            "cache_url": null,
            "name": "2019_TransitAeri_FlightRadar_Ppal_Pais.csv",
            "created": "2024-05-29T09:33:04.915555",
            "url": "https://opendata-ajuntament.barcelona.cat/data/dataset/6ea9c163-e907-49fc-b916-bdddd1448e9e/resource/790b7bb3-cc2a-48d7-82c0-ef51978bceb7/download",
            "downloads_absolute": "87",
            "map_visualization_res": "none",
            "qa": "{'updated': '2026-02-25T02:13:23.889397', 'openness_score': 3, 'archival_timestamp': None, 'format': u'CSV', 'created': '2024-05-31T02:08:40.293933', 'resource_timestamp': None, 'openness_score_reason': u'This file had not been downloaded at the time of scoring it. URL extension \"csv\" relates to format \"CSV\" and receives score: 3.'}",
            "last_modified": null,
            "position": 6,
            "revision_id": "7a87bddf-d3d5-4944-b97f-ea67a7b36a8e",
            "resource_type": null
        }
    ],
    "token_required": "No",
    "decalatgeNum": "1",
    "tags": [
        {
            "vocabulary_id": null,
            "state": "active",
            "display_name": "Aeroport",
            "id": "d07cfad1-126e-4779-a8af-1b1f3a118668",
            "name": "Aeroport"
        },
        {
            "vocabulary_id": null,
            "state": "active",
            "display_name": "Alt Valor",
            "id": "ebe20eba-8f65-40a9-9c25-4e7ab62b8f45",
            "name": "Alt Valor"
        },
        {
            "vocabulary_id": null,
            "state": "active",
            "display_name": "Any 2019",
            "id": "4fdbddac-00a9-480e-a846-8148522b3500",
            "name": "Any 2019"
        },
        {
            "vocabulary_id": null,
            "state": "active",
            "display_name": "Any 2020",
            "id": "2ff883a0-d01a-4af3-8235-8407a6e411a7",
            "name": "Any 2020"
        },
        {
            "vocabulary_id": null,
            "state": "active",
            "display_name": "Any 2021",
            "id": "28ab7cce-e938-4cca-adc6-800b03070775",
            "name": "Any 2021"
        },
        {
            "vocabulary_id": null,
            "state": "active",
            "display_name": "Any 2022",
            "id": "224016e4-81b8-4e60-819b-e7119ced7589",
            "name": "Any 2022"
        },
        {
            "vocabulary_id": null,
            "state": "active",
            "display_name": "Any 2023",
            "id": "3f5176c6-4773-426d-b3f4-729d7d47f59d",
            "name": "Any 2023"
        },
        {
            "vocabulary_id": null,
            "state": "active",
            "display_name": "Any 2024",
            "id": "283fc2f8-cbae-4ef0-9884-edf991193b9f",
            "name": "Any 2024"
        },
        {
            "vocabulary_id": null,
            "state": "active",
            "display_name": "Any 2025",
            "id": "0510e622-4b6e-4f59-994f-41c01b0a8b1f",
            "name": "Any 2025"
        },
        {
            "vocabulary_id": null,
            "state": "active",
            "display_name": "Companyies a\u00e8ries",
            "id": "33666acc-21ac-43c7-8962-bad8c2b1b9b8",
            "name": "Companyies a\u00e8ries"
        },
        {
            "vocabulary_id": null,
            "state": "active",
            "display_name": "Pa\u00efsos",
            "id": "20960c98-7f6e-4670-8068-bd113051b241",
            "name": "Pa\u00efsos"
        },
        {
            "vocabulary_id": null,
            "state": "active",
            "display_name": "Vols",
            "id": "d5418719-80fe-462f-ab53-00145a28e06b",
            "name": "Vols"
        }
    ],
    "ODS_Principal_agenda_2030": "ODS 9: Industria, innovaci\u00f3 i infraestructures",
    "fecha_publicacion": "2024-05-30",
    "ODS_Colateral2_agenda_2030": "N/A",
    "ODS_Colateral1_agenda_2030": "N/A",
    "license_id": "CC-BY-4.0",
    "hide_url": "No",
    "relationships_as_subject": [],
    "license_title": "Creative Commons Attribution 4.0",
    "groups": [],
    "num_resources": 7,
    "organization": {
        "code": "transport",
        "display_name": "Transport",
        "description": "Transport",
        "parent": {
            "code": "entorn-urba",
            "display_name": "Ciutat i serveis",
            "description": "City and Services",
            "created": "2017-01-24T16:55:08.867299",
            "package_count": 0,
            "image_display_url": "https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon2-ciutat-i-serveis",
            "description_translated": {
                "ca": "Ciutat i serveis",
                "en": "City and Services",
                "es": "Ciudad y servicios"
            },
            "name": "entorn-urba",
            "is_organization": true,
            "state": "active",
            "image_url": "bcn-icon2-ciutat-i-serveis",
            "groups": [],
            "type": "organization",
            "title": "City and Services",
            "revision_id": "effe3c8f-e810-4d94-b6a8-3e57540c0802",
            "title_translated": {
                "ca": "Ciutat i serveis",
                "en": "City and Services",
                "es": "Ciudad y servicios"
            },
            "num_followers": 0,
            "id": "d80eb926-faec-4e14-98b9-8c3f0d295977",
            "approval_status": "approved"
        },
        "created": "2017-01-24T16:55:06.928326",
        "package_count": 74,
        "image_display_url": "https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon-transports-publics",
        "tematica_nti": "transporte",
        "description_translated": {
            "ca": "Transport",
            "en": "Transport",
            "es": "Transporte"
        },
        "name": "transport",
        "is_organization": true,
        "state": "active",
        "image_url": "bcn-icon-transports-publics",
        "groups": [
            {
                "capacity": "public",
                "name": "entorn-urba"
            }
        ],
        "type": "organization",
        "title": "Transport",
        "revision_id": "f2d2031d-7973-42f6-8437-d6ee8ad98609",
        "title_translated": {
            "ca": "Transport",
            "en": "Transport",
            "es": "Transporte"
        },
        "num_followers": 0,
        "id": "50bee103-b517-4728-838e-fc0d6b19e91f",
        "approval_status": "approved"
    },
    "name": "transitaeri_flightradar_ppal_pais",
    "url": null,
    "notes": "Number of aircraft operations at the Josep Tarradellas Barcelona-El Prat airport by main destination or origin countries",
    "owner_org": "50bee103-b517-4728-838e-fc0d6b19e91f",
    "load_type": "link_intern_desde_font_interna",
    "api": "Yes",
    "license_url": "https://creativecommons.org/licenses/by/4.0/",
    "historical": "Yes",

In [39]:
# 2. De los resultados obtenidos, selecciona uno que tenga recursos disponibles en CSV o JSON
recurso_id = respuesta_show["result"]["resources"][0]["id"] 

url_data = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/datastore_search"


# 3. Con el recurso_id del recurso seleccionado, realiza una consulta mediante datastore_search por:
# Recuperar al menos 100 registros.
param_datastore = {
    "resource_id": recurso_id,
    "limit": 100
}

data_respuesta = requests.get(url_data, params=param_datastore).json()

records = data_respuesta["result"]["records"]
print(len(records))
print(json.dumps(records[:100], indent=4))

100
[
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Espanya",
        "Nombre_Vols": "230",
        "_id": 1,
        "Codi_Pais": "1"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "It\u00e0lia",
        "Nombre_Vols": "100",
        "_id": 2,
        "Codi_Pais": "2"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Regne Unit",
        "Nombre_Vols": "71",
        "_id": 3,
        "Codi_Pais": "3"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Fran\u00e7a",
        "Nombre_Vols": "83",
        "_id": 4,
        "Codi_Pais": "4"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Alemanya",
        "Nombre_Vols": "48",
        "_id": 5,
        "Codi_Pais": "5"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Portugal",
        "Nombre_Vols": "38",
        "_id": 6,
        "Codi_Pais": "6"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Pa\u00efsos Baixos",
        "Nombre_Vols": "28",
        "_id": 7,
        "Codi_Pais": "7"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Su\u00efssa",
        "Nombre_Vols": "20",
        "_id": 8,
        "Codi_Pais": "8"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "B\u00e8lgica",
        "Nombre_Vols": "20",
        "_id": 9,
        "Codi_Pais": "9"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Marroc, el",
        "Nombre_Vols": "28",
        "_id": 10,
        "Codi_Pais": "10"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Estats Units, els",
        "Nombre_Vols": "11",
        "_id": 11,
        "Codi_Pais": "11"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "\u00c0ustria",
        "Nombre_Vols": "8",
        "_id": 12,
        "Codi_Pais": "12"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Irlanda",
        "Nombre_Vols": "10",
        "_id": 13,
        "Codi_Pais": "13"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Pol\u00f2nia",
        "Nombre_Vols": "14",
        "_id": 14,
        "Codi_Pais": "14"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Turquia",
        "Nombre_Vols": "10",
        "_id": 15,
        "Codi_Pais": "15"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Dinamarca",
        "Nombre_Vols": "8",
        "_id": 16,
        "Codi_Pais": "16"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Romania",
        "Nombre_Vols": "8",
        "_id": 17,
        "Codi_Pais": "17"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Gr\u00e8cia",
        "Nombre_Vols": "4",
        "_id": 18,
        "Codi_Pais": "18"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Su\u00e8cia",
        "Nombre_Vols": "2",
        "_id": 19,
        "Codi_Pais": "19"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Emirats \u00c0rabs Units, els",
        "Nombre_Vols": "6",
        "_id": 20,
        "Codi_Pais": "20"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Tx\u00e8quia",
        "Nombre_Vols": "6",
        "_id": 21,
        "Codi_Pais": "21"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Hongria",
        "Nombre_Vols": "7",
        "_id": 22,
        "Codi_Pais": "22"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Qatar",
        "Nombre_Vols": "6",
        "_id": 23,
        "Codi_Pais": "23"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Noruega",
        "Nombre_Vols": "2",
        "_id": 24,
        "Codi_Pais": "25"
    },
    {
        "Data_Referencia": "2025-01-01T00:00:00",
        "Nom_Pais": "Alg\u00e8ria",
        "Nombre_Vols": "6",
        "_id": 25,
        "Codi_Pais": "26"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Espanya",
        "Nombre_Vols": "263",
        "_id": 26,
        "Codi_Pais": "1"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "It\u00e0lia",
        "Nombre_Vols": "106",
        "_id": 27,
        "Codi_Pais": "2"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Regne Unit",
        "Nombre_Vols": "99",
        "_id": 28,
        "Codi_Pais": "3"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Fran\u00e7a",
        "Nombre_Vols": "83",
        "_id": 29,
        "Codi_Pais": "4"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Alemanya",
        "Nombre_Vols": "64",
        "_id": 30,
        "Codi_Pais": "5"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Portugal",
        "Nombre_Vols": "32",
        "_id": 31,
        "Codi_Pais": "6"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Pa\u00efsos Baixos",
        "Nombre_Vols": "26",
        "_id": 32,
        "Codi_Pais": "7"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Su\u00efssa",
        "Nombre_Vols": "28",
        "_id": 33,
        "Codi_Pais": "8"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "B\u00e8lgica",
        "Nombre_Vols": "20",
        "_id": 34,
        "Codi_Pais": "9"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Marroc, el",
        "Nombre_Vols": "21",
        "_id": 35,
        "Codi_Pais": "10"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Estats Units, els",
        "Nombre_Vols": "13",
        "_id": 36,
        "Codi_Pais": "11"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "\u00c0ustria",
        "Nombre_Vols": "14",
        "_id": 37,
        "Codi_Pais": "12"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Irlanda",
        "Nombre_Vols": "9",
        "_id": 38,
        "Codi_Pais": "13"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Pol\u00f2nia",
        "Nombre_Vols": "18",
        "_id": 39,
        "Codi_Pais": "14"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Turquia",
        "Nombre_Vols": "14",
        "_id": 40,
        "Codi_Pais": "15"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Dinamarca",
        "Nombre_Vols": "10",
        "_id": 41,
        "Codi_Pais": "16"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Romania",
        "Nombre_Vols": "10",
        "_id": 42,
        "Codi_Pais": "17"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Gr\u00e8cia",
        "Nombre_Vols": "6",
        "_id": 43,
        "Codi_Pais": "18"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Su\u00e8cia",
        "Nombre_Vols": "4",
        "_id": 44,
        "Codi_Pais": "19"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Emirats \u00c0rabs Units, els",
        "Nombre_Vols": "6",
        "_id": 45,
        "Codi_Pais": "20"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Tx\u00e8quia",
        "Nombre_Vols": "10",
        "_id": 46,
        "Codi_Pais": "21"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Hongria",
        "Nombre_Vols": "8",
        "_id": 47,
        "Codi_Pais": "22"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Qatar",
        "Nombre_Vols": "6",
        "_id": 48,
        "Codi_Pais": "23"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Noruega",
        "Nombre_Vols": "4",
        "_id": 49,
        "Codi_Pais": "25"
    },
    {
        "Data_Referencia": "2025-01-02T00:00:00",
        "Nom_Pais": "Alg\u00e8ria",
        "Nombre_Vols": "6",
        "_id": 50,
        "Codi_Pais": "26"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Espanya",
        "Nombre_Vols": "254",
        "_id": 51,
        "Codi_Pais": "1"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "It\u00e0lia",
        "Nombre_Vols": "133",
        "_id": 52,
        "Codi_Pais": "2"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Regne Unit",
        "Nombre_Vols": "81",
        "_id": 53,
        "Codi_Pais": "3"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Fran\u00e7a",
        "Nombre_Vols": "93",
        "_id": 54,
        "Codi_Pais": "4"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Alemanya",
        "Nombre_Vols": "64",
        "_id": 55,
        "Codi_Pais": "5"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Portugal",
        "Nombre_Vols": "41",
        "_id": 56,
        "Codi_Pais": "6"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Pa\u00efsos Baixos",
        "Nombre_Vols": "32",
        "_id": 57,
        "Codi_Pais": "7"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Su\u00efssa",
        "Nombre_Vols": "27",
        "_id": 58,
        "Codi_Pais": "8"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "B\u00e8lgica",
        "Nombre_Vols": "21",
        "_id": 59,
        "Codi_Pais": "9"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Marroc, el",
        "Nombre_Vols": "26",
        "_id": 60,
        "Codi_Pais": "10"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Estats Units, els",
        "Nombre_Vols": "12",
        "_id": 61,
        "Codi_Pais": "11"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "\u00c0ustria",
        "Nombre_Vols": "14",
        "_id": 62,
        "Codi_Pais": "12"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Irlanda",
        "Nombre_Vols": "15",
        "_id": 63,
        "Codi_Pais": "13"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Pol\u00f2nia",
        "Nombre_Vols": "12",
        "_id": 64,
        "Codi_Pais": "14"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Turquia",
        "Nombre_Vols": "10",
        "_id": 65,
        "Codi_Pais": "15"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Dinamarca",
        "Nombre_Vols": "10",
        "_id": 66,
        "Codi_Pais": "16"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Romania",
        "Nombre_Vols": "12",
        "_id": 67,
        "Codi_Pais": "17"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Gr\u00e8cia",
        "Nombre_Vols": "8",
        "_id": 68,
        "Codi_Pais": "18"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Su\u00e8cia",
        "Nombre_Vols": "4",
        "_id": 69,
        "Codi_Pais": "19"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Emirats \u00c0rabs Units, els",
        "Nombre_Vols": "8",
        "_id": 70,
        "Codi_Pais": "20"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Tx\u00e8quia",
        "Nombre_Vols": "8",
        "_id": 71,
        "Codi_Pais": "21"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Hongria",
        "Nombre_Vols": "8",
        "_id": 72,
        "Codi_Pais": "22"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Qatar",
        "Nombre_Vols": "6",
        "_id": 73,
        "Codi_Pais": "23"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Noruega",
        "Nombre_Vols": "3",
        "_id": 74,
        "Codi_Pais": "25"
    },
    {
        "Data_Referencia": "2025-01-03T00:00:00",
        "Nom_Pais": "Alg\u00e8ria",
        "Nombre_Vols": "6",
        "_id": 75,
        "Codi_Pais": "26"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Espanya",
        "Nombre_Vols": "233",
        "_id": 76,
        "Codi_Pais": "1"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "It\u00e0lia",
        "Nombre_Vols": "98",
        "_id": 77,
        "Codi_Pais": "2"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Regne Unit",
        "Nombre_Vols": "69",
        "_id": 78,
        "Codi_Pais": "3"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Fran\u00e7a",
        "Nombre_Vols": "75",
        "_id": 79,
        "Codi_Pais": "4"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Alemanya",
        "Nombre_Vols": "62",
        "_id": 80,
        "Codi_Pais": "5"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Portugal",
        "Nombre_Vols": "36",
        "_id": 81,
        "Codi_Pais": "6"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Pa\u00efsos Baixos",
        "Nombre_Vols": "22",
        "_id": 82,
        "Codi_Pais": "7"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Su\u00efssa",
        "Nombre_Vols": "19",
        "_id": 83,
        "Codi_Pais": "8"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "B\u00e8lgica",
        "Nombre_Vols": "16",
        "_id": 84,
        "Codi_Pais": "9"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Marroc, el",
        "Nombre_Vols": "26",
        "_id": 85,
        "Codi_Pais": "10"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Estats Units, els",
        "Nombre_Vols": "13",
        "_id": 86,
        "Codi_Pais": "11"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "\u00c0ustria",
        "Nombre_Vols": "12",
        "_id": 87,
        "Codi_Pais": "12"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Irlanda",
        "Nombre_Vols": "14",
        "_id": 88,
        "Codi_Pais": "13"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Pol\u00f2nia",
        "Nombre_Vols": "14",
        "_id": 89,
        "Codi_Pais": "14"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Turquia",
        "Nombre_Vols": "13",
        "_id": 90,
        "Codi_Pais": "15"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Dinamarca",
        "Nombre_Vols": "8",
        "_id": 91,
        "Codi_Pais": "16"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Romania",
        "Nombre_Vols": "6",
        "_id": 92,
        "Codi_Pais": "17"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Gr\u00e8cia",
        "Nombre_Vols": "5",
        "_id": 93,
        "Codi_Pais": "18"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Su\u00e8cia",
        "Nombre_Vols": "4",
        "_id": 94,
        "Codi_Pais": "19"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Emirats \u00c0rabs Units, els",
        "Nombre_Vols": "6",
        "_id": 95,
        "Codi_Pais": "20"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Tx\u00e8quia",
        "Nombre_Vols": "8",
        "_id": 96,
        "Codi_Pais": "21"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Hongria",
        "Nombre_Vols": "10",
        "_id": 97,
        "Codi_Pais": "22"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Qatar",
        "Nombre_Vols": "6",
        "_id": 98,
        "Codi_Pais": "23"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Noruega",
        "Nombre_Vols": "5",
        "_id": 99,
        "Codi_Pais": "25"
    },
    {
        "Data_Referencia": "2025-01-04T00:00:00",
        "Nom_Pais": "Alg\u00e8ria",
        "Nombre_Vols": "6",
        "_id": 100,
        "Codi_Pais": "26"
    }
]

In [ ]:
# 4. Convierte los resultados a un DataFrame.
df = pd.DataFrame(records)
df.head()

,flight_date,flight_status,departure,arrival,airline,flight,aircraft,live
0,2026-02-25,scheduled,"{'airport': 'Wellington International', 'timez...","{'airport': 'Auckland International', 'timezon...","{'name': 'Air New Zealand', 'iata': 'NZ', 'ica...","{'number': '410', 'iata': 'NZ410', 'icao': 'AN...","{'registration': None, 'iata': None, 'icao': N...",None
1,2026-02-25,scheduled,"{'airport': 'Wellington International', 'timez...","{'airport': 'Auckland International', 'timezon...","{'name': 'Singapore Airlines', 'iata': 'SQ', '...","{'number': '4436', 'iata': 'SQ4436', 'icao': '...","{'registration': None, 'iata': None, 'icao': N...",None
2,2026-02-25,scheduled,"{'airport': 'Wellington International', 'timez...","{'airport': 'Auckland International', 'timezon...","{'name': 'Etihad Airways', 'iata': 'EY', 'icao...","{'number': '4624', 'iata': 'EY4624', 'icao': '...","{'registration': None, 'iata': None, 'icao': N...",None
3,2026-02-25,scheduled,"{'airport': 'Wellington International', 'timez...","{'airport': 'Auckland International', 'timezon...","{'name': 'EVA Air', 'iata': 'BR', 'icao': 'EVA'}","{'number': '3290', 'iata': 'BR3290', 'icao': '...","{'registration': None, 'iata': None, 'icao': N...",None
4,2026-02-25,scheduled,"{'airport': 'Wellington International', 'timez...","{'airport': 'Woodbourne Air Station', 'timezon...","{'name': 'Air New Zealand', 'iata': 'NZ', 'ica...","{'number': '5725', 'iata': 'NZ5725', 'icao': '...","{'registration': None, 'iata': None, 'icao': N...",None

In [ ]:
# 5. Guarda DataFrame en un archivo .csv.
df.to_csv("barcelona_dataset.csv", index=False)